#!/bin/sh -e

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dpam=disabled \
    -Dbash-completions=false \
    -Dfish-completions=false \
    -Dzsh-completions=false \
    . build

ninja -C build
ninja -C build install

chmod a+s "$1/usr/bin/swaylock"

rm -rf "$1/usr/share/zsh/"
rm -rf "$1/usr/share/fish/"
rm -rf "$1/usr/share/bash-completion/"
rm -rf "$1/etc/pam.d/"
