#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --sbindir=/usr/bin \
    --sysconfdir=/etc

make
make DESTDIR="$1" install
