#!/bin/sh -e

patch -p1 < fix-busybox-diff.patch

./configure \
    --prefix=/usr \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --disable-static \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    --as=nasm

make
make DESTDIR="$1" install
