#!/bin/sh -e

patch -p1 < fix-busybox-diff.patch

export CC=clang
export CXX=clang++
export AR=llvm-ar
export LD=ld.lld
export AS=clang
export STRIP=llvm-strip
export NM=llvm-nm

# Determine arch
export triple=$(cc -dumpmachine)
case $triple in
   aarch64-unknown-linux-musl) export _ARCH="armv8-linux-gcc";;
   x86_64-pc-linux-musl) export _ARCH="x86_64-linux-gcc";;
   powerpc64le-unknown-linux-musl) export _ARCH="ppc64le-linux-gcc";;
   *) echo "Unsupported platform."; exit 1;;
esac

echo "Building target: $ARCH"

./configure \
    --prefix=/usr \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --disable-static \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    --as=nasm \
    --target=$_ARCH

make
make DESTDIR="$1" install
