#!/bin/sh -e

# Determine arch
case $KISS_XHOST_ARCH in
   aarch64)     target=linux-aarch64;;
   aarch64_be)  target=linux-aarch64;;
   armv7)       target=linux-generic32;;
   x86_64)      target=linux-x86_64-clang;;
   i686)        target=linux-x86-clang;;
   powerpc)     target=linux-ppc;;
   powerpcle)   target=linux-ppcle;;
   powerpc64le) target=linux-ppc64le;;
   powerpc64)   target=linux-ppc64;;
   riscv64)     target=linux64-riscv64;;
   *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit 1;;
esac

export CFLAGS="$CFLAGS"
export CXXFLAGS="$CXXFLAGS"
export PKG_CONFIG_SYSROOT_DIR=

./Configure \
    --prefix=/usr \
    --openssldir=/etc/ssl \
    --libdir=lib \
    no-unit-test \
    shared \
    $target

make depend
make

make DESTDIR="$1" \
    install_sw \
    install_ssldirs \
    install_man_docs

