#!/bin/sh -e

export PKG_CONFIG_SYSROOT_DIR=

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --libexecdir=/usr/lib \
    -Ddefault_library=both \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=false \
    -Denable-xkbregistry=false \
    -Dxkb-config-extra-path="/usr/share/X11/xkb" \
    . output

ninja -C output
ninja -C output install
