#!/bin/sh -e

export GL_LIBS=""
export GL_CFLAGS=""

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --disable-x11 \
    --enable-wayland

make
make install
