#!/bin/sh -e

: > tests/meson.build

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddebug=false \
    -Djpeg=enabled \
    -Dpng=enabled \
    -Dtiff=disabled \
    -Ddocs=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output
ninja -C output install
