#!/bin/sh -e

export DESTDIR="$1"

kiss-cmake-config > cmake.config

cmake -B build \
	-DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)" \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DWITH_OPENSSL=ON

cmake --build   build
cmake --install build
