#!/bin/sh -e

export CFLAGS="$CFLAGS -fno-lto"
export CXXFLAGS="$CXXFLAGS -fno-lto"

# These cause problems with clang:
rm vp9_rtcd.h
rm vp8_rtcd.h
rm vpx_scale_rtcd.h
rm vpx_dsp_rtcd.h


# Remove the perl requirement from configure.
# Also fix issue with non-GNU diff.
sed 's/perl/:/g;s/diff --version/command -v diff/' configure > _
mv -f _ configure

# Determine arch
case $KISS_XHOST_ARCH in
   aarch64)     target=arm64-linux-gcc;;
   armv7)       target=armv7-linux-gcc;;
   i686)        target=x86-linux-gcc;;
   powerpc64)   target=generic-gnu;;
   powerpc64le) target=ppc64le-linux-gcc;;
   riscv64)     target=generic-gnu;;
   x86_64)      target=x86_64-linux-gcc;;
   *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit 1;;
esac

export CROSS=" "

#     --disable-static \

sh ./configure \
    --prefix=/usr \
    --enable-vp8 \
    --enable-vp9 \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-shared \
    --enable-postproc \
    --enable-pic \
    --disable-tools \
    --disable-examples \
    --disable-docs \
    --disable-unit-tests \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins \
    --as=nasm \
    --target=$target

make
make install
