#!/bin/sh -e

patch -p1 < clang.patch

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --bindir=/usr/bin \
    --disable-python \
    --disable-documentation \
    --disable-backtrace \
    --disable-libudev \
    --disable-static \
    --disable-zstd

make
make install
