#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --bindir=/usr/bin \
    --disable-python \
    --disable-documentation \
    --disable-backtrace \
    --disable-zstd

clang kernel-lib/mktables.c -o mktables

make
make DESTDIR="$1" install
