#!/bin/sh -e

export CFLAGS="$CFLAGS -Wno-format -Wno-implicit-fallthrough"

sed -i 's,#include <sys/sysinfo.h>,,g' common/utils.c

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --bindir=/usr/bin \
    --disable-python \
    --disable-documentation \
    --disable-backtrace \
    --disable-zstd

$CC kernel-lib/mktables.c -o mktables

make
make install
