#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --sysconfdir=/etc/imlib2 \
    --enable-visibility-hiding

make
make DESTDIR="$1" install
