#!/bin/sh -e

export CFLAGS="$CFLAGS -Wno-error -static"

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install

install -Dm755 src/grep "$1/usr/bin/ggrep"
