#!/bin/sh -e

export CFLAGS="$CFLAGS -Wno-error -static"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install

cp -f src/grep "$1/usr/bin/ggrep"
