#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --without-xmlwf \
    --without-examples \
    --without-tests \
    --without-docbook

make
make install

# Remove documentation (Changelogs, etc).
rm -rf "${1:?}/usr/share"
