#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --without-libidn \
    --without-libidn2 \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --without-librtmp \
    --without-icu \
    --without-libpsl \
    --with-pic \
    --with-openssl \
    --with-ca-fallback \
    --enable-static \
    --enable-shared \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make LDFLAGS="$LDFLAGS" CFLAGS="$CFLAGS" curl_LDFLAGS=-all-static
make DESTDIR="$1" install
