#!/bin/sh -e

# Remove bash dependency
sed -i 's/bash -o pipefail/sh /g' Makefile

patch -p1 < musl-ppc.patch
patch -p1 < ppc-revert.patch

# Build qemu-system* binaries dynamically linked
./configure \
    --prefix=/usr \
    --cross-prefix="" \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --cc="$CC" \
    --cxx="$CXX" \
    --host-cc=clang \
    --disable-debug-info \
    --disable-docs \
    --enable-sdl \
    --enable-kvm \
    --enable-pie \
    --enable-curses \
    --cross-prefix="" \
    --disable-gnutls \
    --disable-user \
    --disable-linux-user \
    --enable-vnc \
    --enable-vnc-jpeg \
    --enable-slirp \
    --enable-system

make
make DESTDIR="$1" PREFIX=/usr install
make clean

# Build qemu Linux user binaries statically linked.
./configure \
    --prefix=/usr \
    --cross-prefix="" \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --cc="$CC" \
    --cxx="$CXX" \
    --host-cc=clang \
    --disable-debug-info \
    --disable-docs \
    --disable-gnutls \
    --disable-user \
    --enable-linux-user \
    --disable-system \
    --static

make
make DESTDIR="$1" PREFIX=/usr install
