#!/bin/sh -e

#patch -p1 < cross.patch

export CC_FOR_BUILD=clang
export CFLAGS_FOR_BUILD=-fPIC
export LDFLAGS_FOR_BUILD=""

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --enable-malloc0returnsnull

make
make DESTDIR="$1" install
