#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dintrospection=false \
    . output

ninja -C output
ninja -C output install
