#!/bin/sh -e

sed -i '/chown/d' GNUmakefile

# Needed when cross building
sed -i 's/UID_MAX/65535/g' doas.c
sed -i 's/GID_MAX/65535/g' doas.c

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --enable-static \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make DESTDIR="$1" install

install -Dm600 doas.conf "$1/etc/doas.conf"
