#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 acpid.run         "$1/etc/sv/acpid/run"
ln -s /run/runit/supervise.acpid "$1/etc/sv/acpid/supervise"

# Required otherwise daemon fails to launch.
mkdir -p "$1/etc/acpi/events"
