#!/bin/sh -e

# Uncomment if using valgrind or similar.
#:>nostrip

for p in *.patch; do
    echo "Patch: $p"
    patch -p1 < "$p"
done

# X11-less webrtc patch from bugzilla. Very large so a URL is used.
patch -p1 < attachment.cgi\?id=9202429

# Build autoconf 2.13 for Firefox's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    export CC=clang CXX=clang++ CFLAGS= CXXFLAGS= LDFLAGS=

    cd autoconf2.13

    cp /usr/share/autoconf/build-aux/config.sub config
    cp /usr/share/autoconf/build-aux/config.guess config

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

# Build yasm for Firefox's sole use. Firefox is the only package which needs it
# and upstream is kinda dead.
(
    export CC=clang CXX=clang++ CFLAGS= CXXFLAGS= LDFLAGS=

    cd yasm

    cp /usr/share/autoconf/build-aux/config.sub config
    cp /usr/share/autoconf/build-aux/config.guess config

    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
)

export PATH="$PWD/junk/bin:$PATH"

# If using libc++, CXXSTDLIB needs to be set manually.
export CXXSTDLIB=c++

# Instruct the compiler to trim absolute paths in resulting binaries and instead
# change them to relative paths ($PWD/... ./...).
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox,--enable-new-dtags "
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"
export MACH_USE_SYSTEM_PYTHON=1
export MOZ_DEBUG_FLAGS=-g0
export MOZBUILD_STATE_PATH=$PWD/state
export MOZ_NOSPAM=1

# Cross-build changes
BINDGEN_INCLUDE_FLAGS=$( $CPP -x c++ -v /dev/null -o /dev/null 2>&1 | \
	sed -n '/#include <...> search starts here:/,/End of search list./p' | \
	sed '1,1d;$d' | sed  's/^ /-I/' | paste -s )

export BINDGEN_CFLAGS="--target=$KISS_XHOST_TRIPLE --sysroot=${KISS_ROOT} ${BINDGEN_INCLUDE_FLAGS}"
export HOST_CC="clang"
export TARGET_CC="${CC}"
export HOST_CFLAGS=""
export HOST_CXXFLAGS=""
export ac_cv_sqlite_secure_delete=yes \
       ac_cv_sqlite_threadsafe=yes \
       ac_cv_sqlite_enable_fts3=yes \
       ac_cv_sqlite_dbstat_vtab=yes \
       ac_cv_sqlite_enable_unlock_notify=yes \
       ac_cv_prog_hostcxx_works=1

cat > .mozconfig << EOF
ac_add_options --enable-default-toolkit=cairo-gtk3-wayland
ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/lib
ac_add_options --enable-alsa
ac_add_options --enable-strip
ac_add_options --enable-install-strip
ac_add_options --enable-release
ac_add_options --enable-official-branding
ac_add_options --enable-application=browser
ac_add_options --enable-optimize="${CFLAGS:-} -w"
ac_add_options --with-system-libvpx
ac_add_options --with-system-ffi
ac_add_options --with-system-png
ac_add_options --with-system-jpeg
ac_add_options --with-system-zlib
ac_add_options --with-system-pixman
ac_add_options --without-system-nss
ac_add_options --without-system-nspr
ac_add_options --disable-dbus
ac_add_options --disable-gold
ac_add_options --disable-tests
ac_add_options --disable-vtune
ac_add_options --disable-updater
ac_add_options --disable-jemalloc
ac_add_options --disable-callgrind
ac_add_options --disable-profiling
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-pulseaudio
ac_add_options --disable-accessibility
ac_add_options --disable-debug
ac_add_options --disable-parental-controls
ac_add_options --disable-system-extension-dirs
ac_add_options --target=$KISS_XHOST_TRIPLE
ac_add_options --host=$KISS_XBUILD_TRIPLE
EOF

./mach build
./mach install

# Remove a lot of uneeded "stuff".
rm -rf \
    "$1/usr/include" \
    "$1/usr/lib/firefox-devel" \
    "$1/usr/share/idl" \
    "$1/usr/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi" \
    "$1/usr/lib/firefox/browser/features/screenshots@mozilla.org.xpi" \
    "$1/usr/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi" \
    "$1/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi" \
    "$1/usr/lib/firefox/browser/features/doh-rollout@mozilla.org.xpi"

