#!/bin/sh -e

export CFLAGS="$CFLAGS -Dsigcontext_struct=sigcontext -Werror,-Wno-unused-function"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --enable-mpers=no \
    --enable-silent-rules

make
make install
