#!/bin/sh -e

export CFLAGS="$CFLAGS -Werror,-Wno-unused-function"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --disable-mpers

make
make install
