#!/bin/sh -e

export CFLAGS="$CFLAGS -Dsigcontext_struct=sigcontext"

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --enable-mpers=no \
    --enable-silent-rules

make
make DESTDIR="$1" install
