#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --disable-rpath \
    --disable-doxygen-docs \
    --disable-xmms-plugin \
    --disable-thorough-tests \
    --with-pic

make
make DESTDIR="$1" install
