#!/bin/sh -e

# Remove util-linux dependency among other things.
cat >> Modules/Setup <<EOF
*disabled*
_uuid nis ossaudiodev
EOF


# TODO:
# Don't link to ncurses and readline if present

# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"
export CFLAGS="$CFLAGS -fno-semantic-interposition"
export CXXFLAGS="$CXXFLAGS -fno-semantic-interposition"
export LDFLAGS="$LDFLAGS -fno-semantic-interposition"
export AR=ar
export RANLIB=ranlib
export READELF=readelf

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Detect big endian platforms
if [ "$(cat $KISS_ROOT/etc/os-arch)" == "powerpc64" ]; then
    BIG_ENDIAN=yes
fi

_arch=$(cat ${KISS_ROOT}/etc/os-arch)

ac_cv_file__dev_ptc=yes \
ac_cv_file__dev_ptmx=yes \
ax_cv_c_float_words_bigendian="${BIG_ENDIAN:-no}" \
./configure \
    --prefix=/usr \
    --enable-shared \
    --with-system-expat \
    --with-system-ffi \
    --with-ensurepip=yes \
    --without-doc-strings \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --target="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --enable-shared \
    --disable-ipv6


# Build zlib module explicitly, this is missed when cross building
make
make Modules/zlib.cpython-39-$_arch-linux-gnu.so
make DESTDIR="$1" install

install -Dm644 Modules/zlib.cpython-39-$_arch-linux-gnu.so "$1/usr/lib/python3.9/lib-dynload/zlib.cpython-39-$_arch-linux-gnu.so"

ln -s python3 "$1/usr/bin/python"
ln -s pip3    "$1/usr/bin/pip"

# Make static library writable.
chmod u+w "$1/usr/lib/libpython"*

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
{
    cd "$1/usr/lib/python"*
    rm -rf test ./*/test ./*/tests
    rm -rf pydoc* idlelib turtle* config-* ensurepip

    cd "$1/usr/bin"
    rm -f pydoc* idle*
}
