#!/bin/sh -e

# Remove util-linux dependency among other things.
cat >> Modules/Setup <<EOF
*disabled*
_uuid nis ossaudiodev
EOF

# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"
export CFLAGS="$CFLAGS -fno-semantic-interposition"
export LDFLAGS="$LDFLAGS -fno-semantic-interposition"
export AR=ar
export RANLIB=ranlib
export READELF=readelf
export CPPFLAGS="-I$KISS_ROOT/usr/include"

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Python assuemes readelf is not multi-arch
sed -i 's/readelf|/readelfx|/' configure

if [ $KISS_XHOST_ARCH == "powerpc64" ]; then
    BIG_ENDIAN=yes
fi

# Python has problems determining the build triples
sed -i "s/-linux-gnu/-linux-musl/g" configure
sed -i "s/MULTIARCH=\$(.*/MULTIARCH=$KISS_XHOST_TRIPLE/g" configure

ac_cv_file__dev_ptc=no \
ac_cv_file__dev_ptmx=no \
ax_cv_c_float_words_bigendian="${BIG_ENDIAN:-no}" \
./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --enable-shared \
    --with-system-expat \
    --with-system-ffi \
    --with-ensurepip=yes \
    --without-doc-strings \
    --disable-ipv6

make EXTRA_CFLAGS="$CFLAGS -DTHREAD_STACK_SIZE=0x100000"
make install

ln -s python3 "$1/usr/bin/python"
ln -s pip3    "$1/usr/bin/pip"

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
{
    cd "$1/usr/lib/python"*
    rm -rf test ./*/test ./*/tests
    rm -rf pydoc* idlelib turtle* config-*

    cd "$1/usr/bin"
    rm -f pydoc* idle*
}
