#!/bin/sh -e

# Remove libc header which conflicts with 7 or so Linux
# kernel headers. See: https://github.com/kisslinux/repo/issues/207
sed -i '/net\/if/d' \
    media/mtransport/third_party/nICEr/src/stun/addrs-netlink.c

patch -p1 < disable-moz-stackwalk.patch
#patch -p1 < if_indextoname.patch
patch -p1 < no-gtk2.patch
#patch -p1 < msan.patch

# Build autoconf 2.13 for Firefox's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13

    cp /usr/share/automake-1.16/config.sub .
    cp /usr/share/automake-1.16/config.guess .

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13 \
        --build=$(cc -dumpmachine)

    make
    make install
)

# Build yasm for Firefox's sole use.
# Firefox is the only package which needs it
# and upstream is kinda dead.
(
    cd yasm

    cp /usr/share/automake-1.16/config.sub .
    cp /usr/share/automake-1.16/config.guess .

    ./configure \
        --prefix="$PWD/../junk" \
        --build=powerpc64le-musl-linux

    make
    make install
)

export PATH="$(realpath junk/bin/):$PATH"

mkdir -p build
cd build

# Bypass 'ccache' as it's totally useless when building
# Firefox and only slows things down.
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox "
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0 "
export MOZ_DEBUG_FLAGS=-g
export MOZ_NOSPAM=1
export CXXSTDLIB=c++
export HOST_CXXSTDLIB=c++

export CFLAGS="$CFLAGS -g "
export CXXFLAGS="$CXXFLAGS -g "

../configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-official-branding \
    --enable-optimize="$CFLAGS -w" \
    --enable-install-strip \
    --enable-strip \
    --enable-rust-simd \
    --enable-application=browser \
    --enable-release \
    --enable-alsa \
  --enable-debug \
    --without-system-nspr \
    --without-system-nss \
    --with-system-jpeg \
    --with-system-zlib \
    --with-system-png \
    --without-system-libvpx \
    --with-system-pixman \
    --with-system-ffi \
    --disable-profiling \
    --disable-accessibility \
    --disable-tests \
    --disable-system-extension-dirs \
    --disable-parental-controls \
    --disable-callgrind \
    --disable-vtune \
    --disable-gold \
   --disable-memory-sanitizer \
    --disable-jemalloc \
    --disable-pulseaudio \
    --disable-crashreporter \
    --disable-updater \
    --disable-dbus \
    --disable-necko-wifi \
    --enable-default-toolkit=cairo-gtk3-wayland

make
make DESTDIR="$1" install

# Remove a lot of uneeded "stuff".
rm -rf "$1/usr/include"
rm -rf "$1/usr/lib/firefox-devel"
rm -rf "$1/usr/share/idl"
rm -rf "$1/usr/lib/firefox/gtk2" # Drop GTK+2 runtime dependency.
rm -f  "$1/usr/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/screenshots@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/doh-rollout@mozilla.org.xpi"
