#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests \
    --enable-shared \
    --enable-static \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make DESTDIR="$1" install

install -Dm 755 update-certdata.sh "$1/etc/ssl"
