#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --disable-nls \
    ac_cv_path_DOXYGEN=false

make
make DESTDIR="$1" install
