#!/bin/sh -e

if [ "$KISS_XHOST_ARCH" != "aarch64" ]; then
    echo "This package is for aarch64 only"
    exit 1
fi

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS
export BL31="$KISS_ROOT/usr/share/atf/sun50i_a64/bl31.bin"
export SCP="$KISS_ROOT/usr/share/atf/sun50i_a64/scp.bin"
export PATH="/usr/gnu/bin:$PATH"
export PKG_CONFIG_SYSROOT_DIR=

# Remove gcc reference
sed -i 's/\-lgcc//g' Makefile

make HOSTCC=clang HOSTLD=clang CROSS_COMPILE=aarch64-linux-musl- all

# Install files
mv u-boot-sunxi-with-spl.bin u-boot-sunxi-with-spl-pinephone.bin
mkdir -p "$1/boot/extlinux"
mkdir -p "$1/usr/bin"
cp u-boot-sunxi-with-spl-pinephone.bin $1/boot
cp extlinux.conf $1/boot/extlinux/extlinux.conf.example
