#!/bin/sh
# Print a suitable CMake toolchain file based on $KISS_ROOT

# Create correct CPU string for cmake
case $KISS_XHOST_ARCH in
    armv7)       cpu="arm7l";;
    aarch64)     cpu="aarch64";;
    aarch64_be)  cpu="aarch64_be";;
    i686)        cpu="x86";;
    x86_64)      cpu="x86_64";;
    powerpc64le) cpu="ppc64le";;
    powerpc64)   cpu="ppc64";;
    powerpcle)   cpu="ppcle";;
    powerpc)     cpu="ppc";;
    riscv64)     cpu="riscv64";;
    *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit 1;;
esac

case $KISS_XHOST_ARCH in
    powerpc64)  endian="BIG_ENDIAN";;
    aarch64_be) endian="BIG_ENDIAN";;
    *)          endian="LITTLE_ENDIAN";;
esac

echo "SET(CMAKE_SYSTEM_NAME Linux)"
echo "SET(CMAKE_SYSTEM_VERSION 1)"
echo "SET(CMAKE_C_COMPILER   clang)"
echo "SET(CMAKE_CXX_COMPILER clang++)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)"
echo "SET(CMAKE_FIND_ROOT_PATH  \"${KISS_ROOT}/usr;${KISS_ROOT:-/}\")"
echo "SET(CMAKE_SYSTEM_PROCESSOR ${cpu})"
echo "SET(CMAKE_C_COMPILER_TARGET \"$KISS_XHOST_TRIPLE\")"
echo "SET(CMAKE_CXX_COMPILER_TARGET \"$KISS_XHOST_TRIPLE\")"

# Add crossbuild option if required
if [ -z "$KISS_ROOT" ]; then
    # Normal build
    echo "SET(CMAKE_CROSSCOMPILING FALSE)"
else
    # Cross build
    echo "SET(CMAKE_CROSSCOMPILING TRUE)"
fi
