#!/bin/sh
# Print a suitable CMake toolchain file based on $KISS_ROOT

build_arch="$(cat /etc/os-arch)"
target_arch="$(cat ${KISS_ROOT}/etc/os-arch)"

echo "$(cat /usr/share/cmake/toolchain.cmake)"
echo "SET(CMAKE_FIND_ROOT_PATH  \"${KISS_ROOT}/usr;${KISS_ROOT:-/}\")"

# Add crossbuild options if required
if [ $build_arch != $target_arch  ]; then

    # Create correct CPU string for cmake
    case $target_arch in
        aarch64)     export cpu="aarch64";;
        x86_64)      export cpu="x86_64";;
        powerpc64le) export cpu="ppc64le";;
        powerpc64)   export cpu="ppc64";;
        *) echo "Unsupported platform: $target_arch"; exit 1;;
    esac

    # Cross build
    echo "SET(CMAKE_SYSTEM_PROCESSOR ${cpu})"
    echo "SET(CMAKE_CROSSCOMPILING TRUE)"
else
    # Normal build
    echo "SET(CMAKE_CROSSCOMPILING FALSE)"
fi
