#!/bin/sh
# Print a suitable CMake toolchain file based on $KISS_ROOT

# Create correct CPU string for cmake
case $KISS_XHOST_ARCH in
    armv7)       cpu="arm7l";;
    aarch64)     cpu="aarch64";;
    x86_64)      cpu="x86_64";;
    powerpc64le) cpu="ppc64le";;
    powerpc64)   cpu="ppc64";;
    *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit 1;;
esac

echo "SET(CMAKE_SYSTEM_NAME Linux)"
echo "SET(CMAKE_SYSTEM_VERSION 1)"
echo "SET(CMAKE_C_COMPILER   clang)"
echo "SET(CMAKE_CXX_COMPILER clang++)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)"
echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)"
echo "SET(CMAKE_FIND_ROOT_PATH  \"${KISS_ROOT}/usr;${KISS_ROOT:-/}\")"
echo "SET(CMAKE_SYSTEM_PROCESSOR ${cpu})"

# Add crossbuild option if required
if [ -z "$KISS_ROOT" ]; then
    # Normal build
    echo "SET(CMAKE_CROSSCOMPILING FALSE)"
else
    # Cross build
    echo "SET(CMAKE_CROSSCOMPILING TRUE)"
fi
