#!/bin/sh -e

export CFLAGS="$CFLAGS -DSYS_BASHRC='\"/etc/bash/bashrc\"'"
export CC_FOR_BUILD="clang"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --without-bash-malloc \
    --without-installed-readline \
    --disable-nls

sed -i 's/gcc/clang/g' Makefile

make
make DESTDIR="$1" install

# Provide an alternative
ln -s bash "$1/usr/bin/sh"
