#!/bin/sh -e

arch=$(cat $KISS_ROOT/etc/os-arch)

sed -i 's|/lib|/usr/lib|g' Makefile

make LINKER_PATH=/usr/lib/ld-musl-$arch.so.1
make DESTDIR="$1" install

ln -s ld-linux.so.2 "$1/usr/lib/ld-linux-$arch.so.2"

