#!/bin/sh -e

cp config.sub build-scripts/

# Fixes bug that prevents SDL from building with X11 support
sed -e '/_XData32/s:register long:register _Xconst long:' \
    -i src/video/x11/SDL_x11sym.h

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
