#!/bin/sh -e

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dgles1=true \
    -Dgles2=true \
    -Dtls=false \
    -Dasm=disabled \
    -Dglx=disabled \
    -Dentrypoint-patching=enabled \
     . output

ninja -C output
ninja -C output install
