#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/subdir('tests')//g" meson.build

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dgles1=true \
    -Dgles2=true \
    -Dtls=disabled \
    -Dasm=disabled \
    -Dglx=disabled \
    -Dentrypoint-patching=enabled \
     . output

ninja -C output
ninja -C output install
