#!/bin/sh -e

export DESTDIR="$1"

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dhas-dlvsym=false \
    --cross-file="config.meson" \
    . output

ninja -C output
ninja -C output install
