#!/bin/sh -e

if [ "$KISS_XHOST_ARCH" != "aarch64" ]; then
    echo "This package is for aarch64 only"
    exit 1
fi

patch -p1 < rk3399-baudrate.patch

export PATH=.:/usr/gnu/bin:$PATH
export M0_CROSS_COMPILE="arm-none-eabi-"
export CROSS_COMPILE="aarch64-linux-musl-"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS

mkdir -p $1/usr/share/atf/rk3399 $1/usr/share/atf/sun50i_a64
sed -i 's/\-Wall \-O3 \-nostdlib/\-Wall \-Os \-s \-fno\-PIC \-static \-nostdlib/g' plat/rockchip/rk3399/drivers/m0/Makefile


# Build for rk3399 (Pinebook Pro, RockPro64 etc.)
make DEBUG=0 PLAT=rk3399 bl31
install -Dm644 build/rk3399/release/bl31/bl31.elf "$1/usr/share/atf/rk3399"

# Build for Allwinner A64 (pinephone)
make DEBUG=0 PLAT=sun50i_a64 bl31
install -Dm644 build/sun50i_a64/release/bl31.bin "$1/usr/share/atf/sun50i_a64"
