#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-gtk \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
