#!/bin/sh -e

export CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1"

sed -i 's/ -ltinfo//g' configure

./configure \
    --prefix=/usr \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    --enable-shared \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make -j1
make DESTDIR="$1" install
