#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"
