#!/bin/sh -e

# Required by qt5 and possibly other software.
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1"

#sed -i 's/ -ltinfo//g' configure

ac_cv_search_readline=no \
./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5

#--enable-shared

make
make install
