#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-fontrootdir=/usr/share/fonts/X11 \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
