#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install

ln -s pkgconf "$1/usr/bin/pkg-config"
