#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install

ln -s pkgconf "$1/usr/bin/pkg-config"

# Remove documentation (README, etc).
rm -rf "$1/usr/share/doc"
