#!/bin/sh -e

if [[ "$KISS_XHOST_ARCH" != "x86_64" ]]; then
    echo "This package is only supported on x86_64 targets"
    exit 0
fi

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    --cross-file="config.meson" \
    . build

ninja -C build
ninja -C build install
