#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --without-ndiff \
    --with-openssl=openssl \
    --without-zenmap

make
make DESTDIR="$1" install
