#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --includedir=/usr/include \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-sysroot=$KISS_ROOT

make
make DESTDIR="$1" install

# "make install" puts things in the wrong place
# TODO: fix install script
#mkdir -p "$1/usr/share/man/man4"
#mkdir -p "$1/usr/share/X11/xorg.conf.d"
#mkdir -p "$1/usr/lib/xorg/modules/input"
#mkdir -p "$1/usr/lib/pkgconfig"
mkdir -p "$1/usr/include/xorg"

#install -Dm644 man/libinput.4 "$1/usr/share/man/man4/libinput.4"
#install -Dm644 conf/40-libinput.conf "$1/usr/share/X11/xorg.conf.d/40-libinput.conf"
#install -Dm644 src/.libs/libinput_drv.so "$1/usr/lib/xorg/modules/input/libinput_drv.so"
#install -Dm644 xorg-libinput.pc "$1/usr/lib/pkgconfig/xorg-libinput.pc"
install -Dm644 include/libinput-properties.h "$1/usr/include/xorg/libinput-properties.h"
