#!/bin/sh -e

kiss-meson-config > meson.config

export LDFLAGS="$LDFLAGS -Wl,--undefined-version"

meson setup \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dversion-tag="$2" \
    -Dlibdbus=disabled \
    . output

ninja -C output
ninja -C output install
