#!/bin/sh -e

export CFLAGS="-Wno-unused-but-set-variable"
export PKG_CONFIG_SYSROOT_DIR=

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Dx11-backend=disabled \
    -Drenderers=gles2 \
    . build

ninja -C build
ninja -C build install
