#!/bin/sh -e

patch -p1 < cross.patch

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Ddefault_library=both \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    . build

ninja -C build
ninja -C build install
