#!/bin/sh -e

export DESTDIR="$1"

# Remove 'libelf' and 'util-linux' dependencies.
sed -i 's/HAVE_LIBELF/HAVE_KISS/'      gio/meson.build
sed -i 's/libmount_dep.found()/false/' meson.build

# Don't build tests/fuzzing stuff.
find . -type f -name meson.build -exec \
    sed -i "/subdir('tests')/d;/subdir('fuzzing')/d" {} +

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dfam=false \
    -Dinternal_pcre=true \
    --cross-file="config.meson" \
    . build

ninja -C build
ninja -C build install

# Note: json-glib not building cross ppc64le->aarch64
# Error compiling asm( ... ) statement

kiss l dbus >/dev/null 2>&1 || rm -rf "$1/usr/bin/gdbus"
