#!/bin/sh -e

: > fuzzing/meson.build

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    --cross-file="config.meson" \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dtests=false \
    -Dlibelf=disabled \
    -Dnls=disabled \
    . build

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin/gdbus"
