#!/bin/sh -e

kiss-cmake-config > cmake.config

patch -p1 < clang.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DDISABLE_EXTRA_LIBS=ON \
    -DBUILD_TESTING=OFF

cmake --build   build
cmake --install build
