#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -Werror,-Wno-implicit-fallthrough"
export CXXFLAGS="$CXXFLAGS -Werror,-Wno-implicit-fallthrough"

sed -i "/subdir('tests')/d"    meson.build
sed -i "/subdir('examples')/d" meson.build

meson \
    --prefix=/usr \
    -Dgir=false \
    -Dgtk_doc=false \
    -Dintrospection=disabled \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install
