#!/bin/sh -e

# Determine arch
case $(cat $KISS_ROOT/etc/os-arch) in
   aarch64) arch=arm64;;
   x86_64) arch=x86_64;;
   powerpc64le) arch=powerpc;;
   powerpc64) arch=powerpc;;
   *) echo "Unsupported platform: $(cc -dumpmachine)"; exit;;
esac


# Always use the host compiler here
make LLVM=1 LLVM_IAS=1 ARCH=$arch HOSTCC="clang" headers

# The headers require rsync for installation, this command
# simply does the equivalent using find.
find usr/include -name \*.h -type f | while read -r file; do
    install -Dm644 "$file" "$1/$file"
done
