#!/bin/sh

##########################################################################
# CFLAGS etc. can be set here
#
# To see what values clang supports for a particular arch, try e.g.:
#
#   clang --target=x86_64-linux-musl -march=x86-64 -mcpu=?
#
# ...will show supported CPUs for x86_64. Other architectures
# can be queried in the same way.
#

