#!/bin/sh -e

# Makefile uses a flag which is incompatible with busybox.
sed -i 's/644 -T/644 /g' Makefile

kiss-meson-config > meson.config

meson setup \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dversion-tag="$2" \
    . output

ninja -C output
ninja -C output install

# Remove systemd, dracut and autocompletion files
rm -rf "$1/usr/lib"
rm -rf "$1/etc/udev"
rm -rf "$1/usr/share/zsh"
rm -rf "$1/usr/share/bash-completion"
rm -rf "$1/usr/lib/systemd"
