#!/bin/sh -e

autoreconf -fi

sed -e 's,test "$cross_compiling" = yes, false,' -i configure

for f in $(find . -name Makefile); do
    sed -i $f -e "s;-L/lib;-L${KISS_ROOT}/lib;g"
done

export CFLAGS="$CFLAGS -I${KISS_ROOT}/usr/include"
export CXXFLAGS="$CXXFLAGS -I${KISS_ROOT}/usr/include -I${KISS_ROOT}/usr/include/c++/v1"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-zlib=${KISS_ROOT}/usr/include

make
make install
