#!/bin/sh -e

# config.sub that comes with mtdev is missing aarch64
cp -f config.sub config-aux/

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
