#!/bin/sh -e

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    --cross-file="config.meson" \
    --buildtype=plain \
    -Dgd=disabled \
    -Djpeg=enabled \
    -Dpng=enabled \
    . build

ninja -C build
ninja -C build install
