#!/bin/sh -e

patch -p1 < no-evdev.patch
patch -p1 < llvm-13.patch

export CFLAGS="$CFLAGS"
export PKG_CONFIG_SYSROOT_DIR=

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dxwayland=disabled \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    . build

ninja -C build
ninja -C build install
