#!/bin/sh -e

export LDFLAGS="$LDFLAGS -L$KISS_ROOT/usr/lib"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --disable-static \
    --disable-tiff \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make install
