#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-shared-memory-dir=/dev/shm \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
