#!/bin/sh -e

noasm="-DENABLE_ASSEMBLY=OFF"
# Enabling asm on aarch64 causes build failures
case $KISS_XHOST_ARCH in
   aarch64)    OPTS=$noasm;;
esac

kiss-cmake-config > cmake.config

cmake source \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)" \
    $OPTS \
    -DCMAKE_BUILD_TYPE=Release

cmake --build .
cmake --install .
