#!/bin/sh -e

# Fixes bug that prevents SDL from building with X11 support
sed -e '/_XData32/s:register long:register _Xconst long:' \
    -i src/video/x11/SDL_x11sym.h

# Fix build type detection.
cp /usr/share/libtool/build-aux/config.guess build-scripts/

./configure \
    --prefix=/usr \
    --disable-nls

make
make DESTDIR="$1" install
