#!/bin/sh -e

./configure \
    --prefix=/usr \
    --program-prefix=b \
    --enable-btyacc \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install

ln -s byacc "$1/usr/bin/yacc"
