#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make -C src
make -C include install
make -C src     install

make install-m4dataDATA install-pkgconfigDATA
