#!/bin/sh -e

export CFLAGS="$CFLAGS -lexecinfo"
export CXXFLAGS="$CXXFLAGS -lexecinfo"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install
