#!/bin/sh -e

mkdir tmp

# Build just for the purposes of zic
make CC=clang
make DESTDIR="$(realpath tmp/)" ZICDIR=/usr/bin install

make clean

# What will be installed:
make CC="${CC:-cc}"
make DESTDIR="$1" ZIC="$(realpath tmp/usr/bin/zic)" ZICDIR=/usr/bin install

set -- africa asia australasia europe northamerica southamerica

./tmp/usr/bin/zic -d "$DESTDIR/usr/share/zoneinfo" "$@"
./tmp/usr/bin/zic -d "$DESTDIR/usr/share/zoneinfo/posix" "$@"
./tmp/usr/bin/zic -d "$DESTDIR/usr/share/zoneinfo/right" -L leapseconds "$@"
./tmp/usr/bin/zic -d "$DESTDIR/usr/share/zoneinfo" -p America/New_York
