#!/bin/sh -e

patch -p1 < clang16.patch

#export LDFLAGS="$LDFLAGS -Wl,--undefined-version -L$KISS_ROOT/usr/lib -w"

export CFLAGS="$CFLAGS -Wl,--undefined-version -w -L$KISS_ROOT/usr/lib -w"

./configure \
    --without-debug \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install
