#!/bin/sh -e

# Is the patch required?

export LDFLAGS="$LDFLAGS -L$KISS_ROOT/usr/lib"

./configure \
    --without-debug \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install
