#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make

make -C lib     install
make -C include install

make install-m4dataDATA install-pkgconfigDATA
