#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --disable-gcov

make
make DESTDIR="$1" install
