#!/bin/sh -e

patch -p1 < no-docs.patch

kiss-cmake-config > cmake.config

# -DWITH_SIMD=False \
cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)" \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_SHARED_LIBS=True \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_JPEG8=1

cmake --build   build
cmake --install build
