#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 eiwd.run         "$1/etc/sv/eiwd/run"
ln -s /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
