#!/bin/sh -e

patch -p1 < mandoc-no-warn.patch

sed -i '/int dummy/d' compat_err.c
#sed -i '/int dummy/d' ./compat_*.c
sed -i 's,"more -s","less",g' main.c
#sed -i 's/CC=.*/CC="$CC"/'    configure

# Change default pager.
sed 's,"more -s","less",g' main.c > _
mv -f _ main.c

# Use CC rather than broken default.
sed 's/CC=.*/CC="\$CC"/' configure > _
mv -f _ configure

cat > configure.local <<EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
CC="${CC:-cc}"
CFLAGS="$CFLAGS"
LN="ln -sf"
HAVE_ENDIAN="yes"
HAVE_NANOSLEEP="yes"
EOF

sh ./configure

make
make -j1 base-install

chmod 755 "$1/usr/bin/"*
