#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Patch some vendored files.
for vendor in libc openssl-sys; do
    sed -i 's/\("files":{\)[^}]*/\1/' "vendor/$vendor/.cargo-checksum.json"
done

# Remove links to libgcc_s
sed -i 's/gcc_s/unwind/g' src/libunwind/build.rs

# Determine arch
export triple=$(cc -dumpmachine)
case $triple in
   aarch64-unknown-linux-musl) export ARCH="aarch64";;
   x86_64-pc-linux-musl) export ARCH="x86_64";;
   powerpc64le-linux-musl) export ARCH="powerpc64le";;
esac

echo "Building target: $ARCH"

cat > config.toml <<EOF
[llvm]
link-shared = false
use-libcxx  = true

[build]
build          =   "$ARCH-unknown-linux-musl"
host           = [ "$ARCH-unknown-linux-musl" ]
target         = [ "$ARCH-unknown-linux-musl" ]
docs           = false
compiler-docs  = false
extended       = true
tools          = ["cargo"]
submodules     = false
python         = "python3"
locked-deps    = true
vendor         = true
sanitizers     = false
profiler       = false
full-bootstrap = false
rustc          = "$PWD/$ARCH/bin/rustc"
cargo          = "$PWD/$ARCH/bin/cargo"

[install]
prefix = "/usr"

[rust]
channel           = "stable"
rpath             = true
codegen-units     = 2
codegen-units-std = 2
debuginfo-level   = 0
debug             = false
backtrace         = false
jemalloc          = false
debug-assertions  = false
codegen-tests     = false

[target.$ARCH-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false
EOF

python3 ./x.py build -j "$(($(nproc)-1))"
DESTDIR="$1" python3 ./x.py install
