#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

export CFLAGS="-Wl,--undefined-version"
export CXXFLAGS="-Wl,--undefined-version"

# rust_std is not (yet?) supported by muon, and we should try
# to avoid a hard rust dependency here if possible.
sed "s/, 'rust_std=2021'//" meson.build > _
mv -f _ meson.build

case $KISS_XHOST_ARCH in
   armv7)      GALL=-Dgallium-drivers=panfrost,kmsro,lima,etnaviv,v3d,vc4,swrast LLVM=-Dllvm=enabled VULK=-Dvulkan-drivers=panfrost;;
   aarch64)    GALL=-Dgallium-drivers=panfrost,kmsro,lima,etnaviv,v3d,vc4,swrast LLVM=-Dllvm=enabled VULK=-Dvulkan-drivers=panfrost;;
   i686) ;;
   x86_64) ;; # Auto configured
   powerpc64*) GALL=-Dgallium-drivers=radeonsi,r300,r600,swrast LLVM=-Dllvm=enabled VULK=-Dvulkan-drivers=;;
   riscv64*)   GALL=-Dgallium-drivers=radeonsi,r300,r600,swrast LLVM=-Dllvm=enabled VULK=-Dvulkan-drivers=;;
   *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit;;
esac

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dgles1=enabled \
    -Dgles2=enabled \
    -Degl-native-platform=wayland \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd=true \
    -Ddri-drivers= \
    $VULK \
    $GALL \
    $LLVM \
    . output

# Why does meson ignore sysroot etc?
# Thanks to Void for this:
find -iname "*.ninja" -exec sed -i "{}" \
    -e "s; /usr/lib/; ${KISS_ROOT}/usr/lib/;g" \
    -e "s;-L/usr/lib;-L${KISS_ROOT}/usr/lib;g" \
    -e "s;-I/usr/include;-I${KISS_ROOT}/usr/include;g" \
    -e "s;-isystem;-I${KISS_ROOT};g" \
    \;

ninja -C output
ninja -C output install
