#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Install python-mako which is solely needed for mesa
# and thus contained in this build.
{
    cd mako

    python3 setup.py build
    python3 setup.py install \
        --prefix=/usr \
        --root="$PWD/dist"

    # Use a glob to avoid having to figure out the Python
    # version for the path below.
    cd dist/usr/lib/python*/site-packages

    # Set the PYTHONPATH so python knows where to find mako.
    # The one liner simply appends the existing path and
    # handles the case where an unset PYTHONPATH breaks
    # python as it will only contain our new addition.
    PYTHONPATH=$PWD:$(python -c "import sys; print(':'.join(sys.path))")

    cd -; cd ..
}

export PYTHONPATH
export CFLAGS="$CFLAGS -Wno-implicit-fallthrough "

# Fix build:
#sed -i 's/STN_UNDEF/SHN_UNDEF/g' src/amd/common/ac_rtld.c

case $KISS_XHOST_ARCH in
   armv7)      GALL=-Dgallium-drivers=panfrost,kmsro,lima,etnaviv,v3d,vc4,swrast LLVM=enabled VULK=-Dvulkan-drivers=panfrost;;
   aarch64)    GALL=-Dgallium-drivers=panfrost,kmsro,lima,etnaviv,v3d,vc4,swrast LLVM=enabled VULK=-Dvulkan-drivers=panfrost;;
   x86_64) ;; # Auto configured
   powerpc64*) GALL=-Dgallium-drivers=radeonsi,r300,r600 LLVM=enabled VULK=-Dvulkan-drivers=amd;;
   riscv64*)   GALL=-Dgallium-drivers=radeonsi,r300,r600 LLVM=enabled VULK=-Dvulkan-drivers=amd;;
   *) echo "Unsupported platform: $(cc -dumpmachine)"; exit;;
esac

# Fix issues with musl and firefox.
# https://bugs.freedesktop.org/show_bug.cgi?id=35268
# https://github.com/mesa3d/mesa/commit/9f37c9903b87f86a533bfaffa72f0ecb285b02b2
# https://gitlab.freedesktop.org/mesa/mesa/-/issues/966
sed "/pre_args += '-DUSE_ELF_TLS'/d" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
! kiss l libglvnd >/dev/null 2>&1 || glvnd_enabled=true

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dgles1=true \
    -Dgles2=true \
    -Degl-native-platform=wayland \
    -Dvalgrind=false \
    -Dzstd=false \
    -Dglvnd="${glvnd_enabled:-false}" \
    -Ddri-drivers= \
    $VULK \
    $GALL \
    -Dllvm=$LLVM \
    . output

# Why does meson ignore sysroot etc?
# Thanks to Void for this:
find -iname "*.ninja" -exec sed -i "{}" \
    -e "s; /usr/lib/; ${KISS_ROOT}/usr/lib/;g" \
    -e "s;-L/usr/lib;-L${KISS_ROOT}/usr/lib;g" \
    -e "s;-I/usr/include;-I${KISS_ROOT}/usr/include;g" \
    -e "s;-isystem;-I${KISS_ROOT};g" \
    \;

ninja -C output
ninja -C output install
