#!/bin/sh -e

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --buildtype=release \
    -Dtests=false \
    . output

ninja -C output
ninja -C output install

