#!/bin/sh -e

export CFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export LDFLAGS="$LDFLAGS -fno-lto "
export CC_FOR_BUILD=clang

patch -p1 < cross.patch
patch -p1 < echo-fix.patch

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var

make
make DESTDIR="$1" install
