#!/bin/sh -e

# Remove cflags which cause issues
#export CFLAGS="$CFLAGS -O0 -fno-lto "
export CFLAGS="$CFLAGS -fno-lto"

./configure \
    --prefix=/usr \
    --disable-doc \
    --disable-nls \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make install
