#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --disable-assembler \
    --enable-shared \
    --enable-static \
    --enable-mini-gmp \
    --disable-documentation

make
make install
