#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-included-popt \
    --disable-xxhash \
    --disable-zstd \
    --disable-lz4 \
    --without-included-zlib

make
make install
