#!/bin/sh -e

# Determine what version of compiler-rt is installed
export CLANGVER=$(cat $KISS_ROOT/var/db/kiss/installed/llvm/version | cut -d " " -f 1)

# Determine the name of the compiler-rt library
case $KISS_XHOST_ARCH in
   armv7) ABI="armhf";;
   *)     ABI=$KISS_XHOST_ARCH;;
esac

# Name of final library
libname="ld-$KISS_XHOST_ABI-$ABI.so.1"

# Uncomment if using valgrind or similar.
# :>nostrip

# Building with LTO causes segfaults
export CFLAGS="$CFLAGS -fno-lto"

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make CROSS_COMPILE="" LIBCC="${KISS_ROOT}/usr/lib/clang/$CLANGVER/lib/linux/libclang_rt.builtins-$ABI.a"
make DESTDIR="$1" install

# Create ldd link
mkdir -p $1/usr/bin
ln -s  /usr/lib/ld-musl-$ABI.so.1 "$1/usr/bin/ldd"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/include/sys/tree.h"

# Install getconf.
${CC:-cc} getconf.c -o "$1/usr/bin/getconf"
${CC:-cc} getent.c  -o "$1/usr/bin/getent"
