#!/bin/sh -e

# Determine arch
export triple=$(cc -dumpmachine)

case $triple in
   aarch64-unknown-linux-musl) export LIBARCH="aarch64";;
   x86_64-pc-linux-musl) export LIBARCH="x86_64";;
esac

echo "Building target: $LIBARCH"

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib

make
make DESTDIR="$1" install

mkdir -p "$1/usr/bin"
ln -s /usr/lib//usr/lib/ld-musl-$LIBARCH.so.1 "$1/usr/bin/ldd"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/include/sys/tree.h"

# Install getconf.
cc getconf.c -o "$1/usr/bin/getconf"

