#!/bin/sh -e

# Fix CVE-2020-28929. This will be fixed upstream in version 1.2.2.
for patch in *.patch; do
    patch -p1 < "$patch"
done

# Disable lto
# Example: https://github.com/InBetweenNames/gentooLTO/issues/244
export CFLAGS=$(echo $CFLAGS | sed -r 's/(-flto){1}(=?)(\w*)( ?)//g')
export CXXFLAGS=$(echo $CXXFLAGS | sed -r 's/(-flto){1}(=?)(\w*)( ?)//g')
export LDFLAGS=$(echo $LDFLAGS | sed -r 's/(-flto){1}(=?)(\w*)( ?)//g')
export CLANGVER=$(cat /var/db/kiss/installed/llvm/version | cut -d " " -f 1)

# Uncomment if using valgrind or similar.
# :>nostrip

TARGET="$(cat ${KISS_ROOT}/etc/os-arch)"

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="${TARGET}-linux-musl"

make CROSS_COMPILE="" LIBCC="${KISS_ROOT}/usr/lib/clang/$CLANGVER/lib/linux/libclang_rt.builtins-$TARGET.a"
make DESTDIR="$1" install

mkdir -p "$1/usr/bin"
ln -s  /usr/lib/ld-musl-${TARGET}.so.1 "$1/usr/bin/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/usr/lib/ld-musl-$TARGET.so.1"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/include/sys/tree.h"

# Install getconf.
cc getconf.c -o "$1/usr/bin/getconf"
cc getent.c  -o "$1/usr/bin/getent"
