#!/bin/sh -e

export LDFLAGS="$LDFLAGS -Wl,--undefined-version"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sysconfdir=/etc \
    --enable-static \
    --disable-gssapi

make
make install
