#!/bin/sh -e

# Don't link to libexecinfo if it is present
patch -p1 < cmake-no-execinfo.patch

# Check for cmake on the build machine
if [ -d "/var/db/kiss/installed/cmake" ]; then

    export DESTDIR="$1"

    kiss-cmake-config > cmake.config
    echo "SET(CMake_RUN_CXX_FILESYSTEM ON)"                >> cmake.config
    echo "SET(CMake_RUN_CXX_FILESYSTEM__TRYRUN_OUTPUT ON)" >> cmake.config

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=True \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DBUILD_CursesDialog=0 \
        -DBUILD_TESTING=OFF \
        -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)"

    cmake --build   build
    cmake --install build

else

   # If cmake doesn't exist on the host machine, use classic config
   # Since this will always be for the build machine, we don't need
   # cross build options here

    ./configure \
        --prefix=/usr \
        --system-curl \
        --system-expat \
        --system-zlib \
        --system-bzip2

    make
    make DESTDIR="$1" install
fi

rm -rf "$1/usr/doc"
rm -rf "$1/usr/share/cmake"*/Help

install -Dm755 kiss-cmake-config "$1/usr/bin/kiss-cmake-config"
