#!/bin/sh -e

export DESTDIR="$1"

kiss-meson-config > config.meson

meson \
    --prefix=/usr \
    -Denable-docs=false \
    -Denable-wayland=false \
    -Denable-xkbregistry=false \
    --cross-file="config.meson" \
    . output

ninja -C output
ninja -C output install
