#!/bin/sh -e

export LDFLAGS="$LDFLAGS -Wl,--undefined-version"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-threads \
    --with-history \
    --without-python \
    --without-icu

make
make install
