#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --with-threads \
    --with-history \
    --without-python \
    --without-icu

make
make DESTDIR="$1" install
