#!/bin/sh -e

# Disable documentation (READMEs and such).
sed 's/^\(dist_doc_DATA\)/\1_null/' Makefile.in > _
mv -f _ Makefile.in

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sbindir=/usr/bin \
    --mandir=/usr/share/man \
    --enable-compat-symlinks

make
make install
