#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --sbindir=/usr/bin \
    --mandir=/usr/share/man \
    --enable-compat-symlinks

make
make DESTDIR="$1" install
