#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
NO_ICONV=YesPlease
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes \
    ac_cv_iconv_omits_bom=no


LIBS="$KISS_ROOT/usr/lib/libcurl.a --sysroot=$KISS_ROOT/usr -L$KISS_ROOT/usr/lib -lssl -lcrypto -lssl -lcrypto -lz"

make LIBS="$LIBS libgit.a xdiff/lib.a"
make install

cp -Rf man "$1/usr/share/man"
