#!/bin/sh -e

export CFLAGS="$CFLAGS -static -L${KISS_ROOT}/usr/lib "

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
NO_ICONV=YesPlease
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes \
    ac_cv_iconv_omits_bom=no

make LIBS="$(curl-config --static-libs) libgit.a xdiff/lib.a -lz"
make install

cp -Rf man "$1/usr/share/man"
