#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --with-xinitdir=/etc/X11/xinit

make
make DESTDIR="$1" install

# Make xauth optional.
sed -i 's#enable_xauth=1#command -v xauth >/dev/null \&\&&||enable_xauth=0#' \
    "$1/usr/bin/startx"
