#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-xinitdir=/etc/X11/xinit

make
make DESTDIR="$1" install

# Make xauth optional.
sed -i 's#enable_xauth=1#command -v xauth >/dev/null \&\&&||enable_xauth=0#' \
    "$1/usr/bin/startx"
