#!/bin/sh -e

patch -p1 < ppc64.patch

# LTO causes problems
export CFLAGS="$CFLAGS -fno-lto"
export CXXFLAGS="$CXXFLAGS -fno-lto"

case $KISS_XHOST_ARCH in
   aarch64)     target=aarch64;;
   armv7)       target=armv7;;
   i686)        target=i686;;
   powerpc64)   target=ppc64;;
   powerpc64le) target=ppc64;;
   riscv64)     target=riscv64;;
   x86_64)      target=x86_64;;
   *) echo "Unsupported platform: $KISS_XHOST_ARCH"; exit 1;;
esac

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --host-cc="clang" \
    --prefix=/usr \
    --sysroot="${KISS_ROOT:-/}" \
    --target-os=linux \
    --arch=$target \
    --enable-shared \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-openssl \
    --enable-libass \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libdrm \
    --x86asmexe=nasm \
    --disable-debug \
    --enable-cross-compile \
    --disable-libxml2

sed -i 's/gcc/clang/g' ffbuild/config.mak

make
make install

rm -rf "$1/usr/share/ffmpeg/examples"
