#!/bin/sh -e

case $(cat $KISS_ROOT/etc/os-arch) in
   aarch64) target=aarch64;;
   x86_64) target=x86_64;;
   powerpc64le) target=ppc64;;
   powerpc64) target=ppc64;;
   *) echo "Unsupported platform: $(cc -dumpmachine)"; exit;;
esac

patch -p1 < ppc64.patch

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --dep-cc="${CC:-cc}" \
    --prefix=/usr \
    --disable-cross-compile \
    --sysroot=${KISS_ROOT:-/} \
    --target-os=linux \
    --arch=$target \
    --enable-shared \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-openssl \
    --enable-libass \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libdrm \
    --x86asmexe=nasm \
    --disable-debug \
    --enable-cross-compile \
    --disable-libxml2

sed -i 's/gcc/clang/g' ffbuild/config.mak

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/ffmpeg/examples"
