#!/bin/sh -e

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --enable-noexecstack \
    --disable-nls

make
make install
