#!/bin/sh -e

export DESTDIR="$1"

pkg-config --exists libudev || {
    printf 'udev (or libudev-zero) is required\n'
    exit 1
}

kiss-meson-config > config.meson
#echo -e "\n\n[binaries]\npkgconfig = 'pkgconf'" >> config.meson

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    -Dudev="${udev:=true}" \
    --cross-file="config.meson" \
    . output

ninja -C output
ninja -C output install
