#!/bin/sh -e

kiss-meson-config > meson.config

meson setup \
    -Dprefix=/usr \
    --cross-file="meson.config" \
    -Degl=yes \
    -Dtests=false \
    -Dglx=no \
    -Dx11=false \
    output

ninja -C output
meson install -C output
