#!/bin/sh -e

kiss-meson-config > meson.config

# -Dhas-dlvsym=false \

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dglx=no \
    -Dx11=false \
    . output

ninja -C output
ninja -C output install
