#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --disable-nls \
    --with-nettle-mini \
    --with-included-libtasn1 \
    --with-included-unistring \
    --enable-static \
    --with-p11-kit

make
make DESTDIR="$1" install
