#!/bin/sh -e

export LDFLAGS="$LDFLAGS -L$KISS_ROOT/usr/lib"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --enable-unicode-properties

make
make install

rm -rf "$1/usr/share/doc"
