#!/bin/sh -e

build_freetype() (
    cd freetype
    kiss-meson-config > meson.cross

    meson \
        --prefix=/usr \
        --cross-file="meson.cross" \
        -Ddefault_library=both \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        "$@" \
        . output

    # Fix linking on cross build
    sed -i "s| /usr/lib/libharfbuzz.so| $DESTDIR/usr/lib/libharfbuzz.so|g" output/build.ninja

    ninja -C output
    ninja -C output install
)


build_harfbuzz() (

    # Point Harfbuzz to the Freetype files.
    export CFLAGS="$CFLAGS -I$1/usr/include/freetype2"
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    cd harfbuzz
    kiss-meson-config > meson.cross

    meson \
        --prefix=/usr \
        --cross-file="meson.cross" \
        -Dpkg_config_path="$DESTDIR/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    # Fix linking on cross build
    sed -i "s| /usr/lib/libfreetype.so| $DESTDIR/usr/lib/libfreetype.so|g" output/build.ninja

    ninja -C output
    ninja -C output install
)


# Point Freetype to the Harfbuzz files.
export CFLAGS="$CFLAGS -I$DESTDIR/usr/include/harfbuzz"
export CFLAGS="$CFLAGS -L$DESTDIR/usr/lib "
export PKG_CONFIG_PATH=$DESTDIR/usr/lib/pkgconfig

# Point Harfbuzz to the Freetype files.
export CXXFLAGS="$CXXFLAGS -I$DESTDIR/usr/include/freetype2"
export CXXFLAGS="$CXXFLAGS -L$DESTDIR/usr/lib"

build_freetype -Dharfbuzz=disabled
build_harfbuzz
build_freetype -Dharfbuzz=enabled --reconfigure
