#!/bin/sh -e

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed 's/xml2lst\.pl/xml2lst/' rules/meson.build > _
mv -f _ rules/meson.build

# Remove po/ dir.
sed "/subdir('po')/d" meson.build > _
mv -f _ meson.build

kiss-meson-config > meson.config

meson setup \
    -Dprefix=/usr \
    --cross-file=meson.config \
    output

ninja -C output
ninja -C output install
