#!/bin/sh -e

#--enable-malloc0returnsnull

./configure \
    --prefix=/usr \
    --enable-malloc0returnsnull \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
