#!/bin/sh -e

#--enable-malloc0returnsnull

./configure \
    --prefix=/usr \
    --enable-malloc0returnsnull \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE

make
make DESTDIR="$1" install
