#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --without-xmlto \
    --disable-specs \
    --enable-static \
    --enable-malloc0returnsnull

make
make DESTDIR="$1" install

# This will be removed once 'xorgproto' 2019.2
# is released.
rm -f "$1/usr/include/X11/extensions/XKBgeom.h"
