#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --with-xkb-path=/usr/share/X11/xkb \
    --with-xkb-output=/usr/share/X11/xkb/compiled \
    --with-xkb-bin-directory=/usr/bin \
    --localstatedir=/var \
    --disable-systemd-logind \
    --disable-xwayland \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-xorg \
    --with-sha1=libcrypto \
    --with-systemd-daemon=off \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-sysroot=${KISS_ROOT:-/} \
    --exec-prefix=/usr

make
make DESTDIR="$1" install
