#!/bin/sh -e

patch -p1 < rootless_modesetting.patch

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --with-xkb-path=/usr/share/X11/xkb \
    --with-xkb-output=/usr/share/X11/xkb/compiled \
    --with-xkb-bin-directory=/usr/bin \
    --localstatedir=/var \
    --disable-systemd-logind \
    --disable-xwayland \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-xorg \
    --with-sha1=libcrypto \
    --with-systemd-daemon=off \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
