#!/bin/sh -e

patch -p1 < nojsonc.patch

./configure \
    AUTOMAKE=/bin/true \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-docs \
    --disable-nls \
    --disable-jsonc \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl"

make
make DESTDIR="$1" install
