#!/bin/sh -e

#export CFLAGS="$CFLAGS -I$KISS_ROOT/usr/include/freetype2"

# Make the build system run /bin/true to generate
# a dummy file so our pre-generated one is used.
sed 's/fcobjshash\.h/fcjunk.h/' src/Makefile.in > _
mv -f _ src/Makefile.in

./configure \
    GPERF=/bin/true \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-sysroot="${KISS_ROOT}/usr" \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-docs \
    --disable-nls

make
make install
