#!/bin/sh -e

patch -p1 < libtheora-1.1.1-libpng16.patch
patch -p1 < fix-theoraenc.patch

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --disable-sdltest \
    --disable-examples \
    --disable-vorbistest

#make
#make install

make
make -C lib     install
make -C include install
make install-pkgconfigDATA
