#!/bin/sh -e

patch -p1 < cmake-no-execinfo.patch

export DESTDIR="$1"

kiss-cmake-config > toolchain.cmake
echo "SET(CMake_RUN_CXX_FILESYSTEM ON)"                >> toolchain.cmake
echo "SET(CMake_RUN_CXX_FILESYSTEM__TRYRUN_OUTPUT ON)" >> toolchain.cmake

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_USE_SYSTEM_CURL=True \
    -DCMAKE_USE_SYSTEM_EXPAT=True \
    -DCMAKE_USE_SYSTEM_ZLIB=True \
    -DCMAKE_USE_SYSTEM_BZIP2=True \
    -DBUILD_CursesDialog=0 \
    -DBUILD_TESTING=OFF \
    -DCMAKE_TOOLCHAIN_FILE="$(realpath toolchain.cmake)"

cmake --build   build
cmake --install build

rm -rf "$1/usr/doc"
rm -rf "$1/usr/share/cmake"*/Help

#mkdir -p "$1/usr/share/cmake"
install -Dm644 crossbuild.cmake  "$1/usr/share/cmake/toolchain.cmake"
install -Dm755 kiss-cmake-config "$1/usr/bin/kiss-cmake-config"
