#!/bin/sh -e

# Fix python 3.
sed -i 's|(3, 8)|(3, 9), (3, 8)|g' configure

# Don't link with libatomic on clang systems.
sed -i "s/\\'libraries\\'\\: \\[\\'-latomic\\'\\],/#/g"   node.gyp
sed -i "s/\\'libraries\\': \\[\\'-latomic\\', \\],/###/g" tools/v8_gypfiles/v8.gyp

# ppc fix:
sed -i "s/, '-mminimal-toc'//g" common.gypi

# Confirm if these are not needed now:
#export CFLAGS="$CFLAGS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
#export CXXFLAGS="$CXXFLAGS -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -lc++abi -lc++"

case $(cc -dumpmachine) in
   aarch64-glasnost-linux-musl) ;;
   x86_64-glasnost-linux-musl) ;;
   powerpc64le-glasnost-linux-musl) ;;
   powerpc64-glasnost-linux-musl) GFLAGS="--dest-cpu=ppc64 --openssl-no-asm";;
   *) echo "Unsupported platform: $(cc -dumpmachine)"; exit;;
esac


./configure \
    --shared-zlib \
    --with-intl=small-icu \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    $GFLAGS \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf "$1/usr/include/node/openssl"
rm -rf "$1/usr/lib/node_modules/npm/scripts"
rm -f  "$1/usr/lib/node_modules/npm/configure"
