#!/bin/sh -e

# Fix python 3.
sed -i 's|(3, 8)|(3, 9), (3, 8)|g' configure

# Don't link with libatomic on clang systems.
sed -i "s/\\'libraries\\'\\: \\[\\'-latomic\\'\\],/#/g"   node.gyp
sed -i "s/\\'libraries\\': \\[\\'-latomic\\', \\],/###/g" tools/v8_gypfiles/v8.gyp

# ppc fix:
sed -i "s/, '-mminimal-toc'//g" common.gypi

export CC=clang
export CXX=clang++

./configure \
    --shared-zlib \
    --with-intl=small-icu \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf "$1/usr/include/node/openssl"
rm -rf "$1/usr/lib/node_modules/npm/scripts"
rm -f  "$1/usr/lib/node_modules/npm/configure"
