#!/bin/sh -e

export PATH="/usr/gnu/bin:$PATH"
export CROSS_COMPILE="or1k-elf-"

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

# Clang does not support -fvar-tracking-assignments
sed -i 's/-fvar-tracking-assignments//g' Makefile

make HOSTCC=clang pinephone_defconfig
make build/scp/scp.bin

mkdir -p $1/usr/share/atf/sun50i_a64
cp build/scp/scp.bin $1/usr/share/atf/sun50i_a64
