#!/bin/sh -e

case $(cat $KISS_ROOT/etc/os-arch) in
   x86_64) ;;
   *) echo "Unsupported platform: $(cc -dumpmachine)"; exit 1;;
esac


export DESTDIR="$1"

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    . output

ninja -C output
ninja -C output install
