#!/bin/sh -e

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    . output

ninja -C output
ninja -C output install
