#!/bin/sh -ef

make PREFIX=/usr
make PREFIX=/usr install

mkdir -p "$1/usr/bin"

# Intentional, globbing disabled.
# shellcheck disable=2086
clang -static $LDFLAGS $CFLAGS $CPPFLAGS \
    -o "$1/usr/bin/libudev-zero-helper" contrib/helper.c

