#!/bin/sh -e

patch -p1 < no-add-needed.patch

#CCLD="clang"
export CFLAGS="$CFLAGS -Wno-unused-command-line-argument"

# Disable test program 'thread-test' as it causes build failures when using
# parallel make (due to missing dependency on libefivar.so). Other workarounds
# include patching the Makefile or forcing -j1 (what we used to do).
# See: https://github.com/rhboot/efivar/pull/169
sed 's/thread-test//' src/Makefile > _
mv -f _ src/Makefile

export HOSTCC="clang"
export HOST_CFLAGS=""
export HOST_LDFLAGS=""

make HOST_MARCH="" COMPILER="$CC"
make libdir=/usr/lib/ install
