#!/bin/sh -e

export SDL_CONFIG="$KISS_ROOT/usr/bin/sdl-config"
export CPPFLAGS="$CXXFLAGS -I${KISS_ROOT}/usr/include/SDL"
export CFLAGS="$CFLAGS -I${KISS_ROOT}/usr/include/SDL"

patch -p1 < cross.patch

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --disable-opengl \
    --disable-sdltest

make
make DESTDIR="$1" install
