#!/bin/sh -e

patch -p1 < no-fribidi.patch

# Disable download of missing (optional) dependencies
# during the build. This cannot be turned off otherwise.
rm -rf subprojects

: > tests/meson.build
: > examples/meson.build
: > docs/meson.build

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dintrospection=disabled \
    -Dinstall-tests=false \
    . build

ninja -C build
ninja -C build install
