#!/bin/sh -e

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --mandir=/usr/share/man \
    --localstatedir=/var

make
make DESTDIR="$1" install
