#!/bin/sh -e

export PKG_CONFIG_SYSROOT_DIR=
export HOST_CC=clang
export HOST_CC=clang
export TARGET=visurf
export PREFIX=/usr
export LIBDIR=lib
export INCLUDEDIR=include
export BUILD="$KISS_XBUILD_TRIPLE"
export HOST="$KISS_XHOST_TRIPLE"

patch -p1 < nsgenbind.patch

rm -Rf netsurf
rm -Rf libcss
mv visurf netsurf
mv libcss-new libcss

# Something up with how kiss does the git checkout
# Not dealing with symlink correctly?
touch netsurf/frontends/visurf/res/Messages

make
make install
