#!/bin/sh -e

./autogen.sh

# Fix build with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sysconfdir=/etc \
    --enable-cgroup \
    --enable-unicode \
    --enable-taskstats

make
make install
