#!/bin/sh -e

# Fix build with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat $KISS_ROOT/etc/os-arch)-linux-musl" \
    --sysconfdir=/etc \
    --enable-cgroup \
    --enable-unicode \
    --enable-taskstats

make
make DESTDIR="$1" install
