#!/bin/sh -e

#export MOREFLAGS="-logg -lopus -lvorbis -lvorbisenc -lFLAC"
export DESTDIR="$1"

kiss-cmake-config > cmake.config

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_TOOLCHAIN_FILE="$(realpath cmake.config)" \
    -DENABLE_NLS="off" \
    -DCMAKE_C_FLAGS="$CFLAGS $MOREFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS $MOREFLAGS"

cmake --build   build
cmake --install build

# Install themes
mkdir -p "$1/usr/share/icewm/themes"
cp -r themes/data/* "$1/usr/share/icewm/themes"
chmod -R go-w "$1/usr/share/icewm/themes"
