#!/bin/sh -e

export DESTDIR="$1"

kiss-meson-config > meson.config

export CFLAGS="$CFLAGS -lgnutls"

meson \
    --prefix=/usr \
    --cross-file="meson.config" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dlibproxy=disabled \
    -Dopenssl=disabled \
    -Dgnutls=enabled \
    . output

ninja -C output
ninja -C output install
