#!/bin/sh -e

export CFLAGS="$CFLAGS -Wno-incompatible-function-pointer-types"
export CXXFLAGS="$CXXFLAGS -Wno-incompatible-function-pointer-types"

patch -p1 < portability.patch

./configure \
    --prefix=/usr \
    --host=$KISS_XHOST_TRIPLE \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

make
make install
