#!/bin/sh -e

export CFLAGS="$CFLAGS -fno-lto"
export CXXFLAGS="$CXXFLAGS -fno-lto"

patch -p1 < portability.patch

./configure \
    --prefix=/usr \
    --host=$KISS_XHOST_TRIPLE \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

make
make install
