#!/bin/sh -e

(
    cd inih

    export DESTDIR="$PWD/../libinih"

    kiss-meson-config > meson.config

    meson \
        -Dprefix=/ \
        --cross-file="meson.config" \
        -Ddefault_library=static \
        -Ddistro_install=true \
        -Dwith_INIReader=true \
        -Dmulti-line_entries=true \
        -Dutf-8_bom=true \
        -Dinline_comments=true \
        -Duse_heap=false \
        . output

    ninja -C output
    ninja -C output install
)

export CFLAGS="$CFLAGS -I$PWD/libinih/include"
export LDFLAGS="$LDFLAGS -L$PWD/libinih/lib"

# Remove incorrect bash dependency.
sed -i 's/bash/sh/' install-sh
sed -i 's/SIGKILL/9/g' include/linux.h

./configure \
    --prefix=/usr \
    --build="$(cat /etc/os-arch)-linux-musl" \
    --host="$(cat ${KISS_ROOT}/etc/os-arch)-linux-musl" \
    --sbindir=/usr/bin \
    --disable-gettext

make
make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/usr/bin \
    PKG_ROOT_LIB_DIR=/usr/lib \
    install
