#!/bin/sh -e

export BUILD_ZLIB=0
export BUILD_BZIP2=0
export LDFLAGS="$LDFLAGS -pthread -fno-lto"
export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE -D_GNU_SOURCE -fno-lto "

export CC=clang
export CXX=clang++

#export byteorder="12345678"

if [ $KISS_XBUILD_TRIPLE != $KISS_XHOST_TRIPLE ]; then
    crossopt=-Dusecrosscompile
fi

./configure \
    --prefix=/usr \
    --target="$KISS_XHOST_TRIPLE" \
    --build="$KISS_XBUILD_TRIPLE" \
    --sysroot="${KISS_ROOT:-/}" \
    -Dbyteorder="12345678" \
    -Des \
    -Dvendorprefix=/usr \
    -Dusevendorprefix \
    -Duseshrplib \
    -Dusesoname \
    -Dusethreads \
    -Dccflags="$CFLAGS" \
    -Dccdlflags="$CFLAGS" \
    -Dcccdlflags="$CFLAGS" \
    -Dlddlflags="$CFLAGS -shared" \
    -Dshrpldflags="$CFLAGS" \
    -Dldflags="$CFLAGS $LDFLAGS" \
    -Dlkflags="$CFLAGS" \
    -Doptimize="-Wall" \
    $crossopt \
    -Dar="${AR:-ar}" \
    -Dnm="${NM:-nm}" \
    -Dranlib="${RANLIB:-ranlib}" \
    -Dreadelf="${READELF:-readelf}" \
    -Dobjdump="${OBJDUMP:-objdump}" \
    -Dinc_version_list=none \
    -Dd_sockaddr_in6=define \
    -Dcccdlflags=-fPIC \
    -Dlddlflags="-shared $CFLAGS $LDFLAGS" \
    -Dperl_static_inline="static __inline__" \
    -Dd_static_inline

make
make DESTDIR="$1" install

# Remove all unneeded files.
find "$1" -name \*.pod       -exec rm -f {} +
find "$1" -name .packlist    -exec rm -f {} +
find "$1" -name README\*     -exec rm -f {} +
find "$1" -name TODO\*       -exec rm -f {} +
find "$1" -name Change\*     -exec rm -f {} +
find "$1" -name \*.bs        -exec rm -f {} +

# Fix permissions.
find "$1/usr/lib" -type f -exec chmod 644 {} \;
