#!/bin/sh -e

patch -p1 < cross.patch

export CROSS_COMPILE=""

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --with-sysdeps="$KISS_ROOT/usr/lib/skalibs/sysdeps" \
    --with-lib="$KISS_ROOT/usr/lib/skalibs" \
    --with-dynlib="$KISS_ROOT/usr/lib/skalibs" \
    --with-include="$KISS_ROOT/usr/include" \
    --enable-static-libc

make
make install

mkdir -p "$1/etc/sv/mdevd"
cp -f mdevd.conf "$1/etc"
cp -f mdevd.run  "$1/etc/sv/mdevd/run"
ln -sf "/run/runit/supervise.mdevd" "$1/etc/sv/mdevd/supervise"
rm -rf "$1/usr/include"
