#!/bin/sh -e

# Disable lto
export CFLAGS="$CFLAGS -fno-lto"
export CXXFLAGS="$CXXFLAGS -fno-lto"

patch -p1 < x264-no-bash.patch

export CC=clang
export CXX=clang++

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

make
make DESTDIR="$1" install
