#!/bin/sh -e

python setup.py build
python setup.py install \
    --root="$1" \
    --optimize=1 \
    --skip-build

# Install files used for cross building
mkdir -p "$1/usr/share/meson"
install -Dm755 kiss-meson-config "$1/usr/bin/kiss-meson-config"
